### ISSUE TITLE
Imported component not shown as dependency (vue)

### ISSUE THREAD

**Issue by puyt** [atanasster/storybook-addon-deps#11]
Hi,

Thanks for your fast update with the storybook 6 release but I can't seem to get it to work for my Vue project, am I doing something wrong? I want to use this addon to display the dependencies with other components. 

Simple example: I have 2 components BButton.vue & BIcon.vue, the BIcon.vue is used in BButton.vue
[test-sb-deps.zip](https://github.com/atanasster/storybook-addon-deps/files/5079190/test-sb-deps.zip)

So I on the BIcon docs I want that it's used in BButton and for BButton I want to see it has a dependency of the BIcon component.

Also can I get rid of the other dependencies as seen in the screen below?

![image](https://user-images.githubusercontent.com/3668615/90317746-bca8fa80-df2b-11ea-9c0b-36c8926c3018.png)

Thanks in advance!

**Comment by atanasster** [comment]
Thanks @puyt for the sample - getting on it and will post as soon as I figure out the dependency issue.

As for filtering dependencies - which dependencies do you want to hide? There is an option to only show dependencies that do have a story written for them (so it will hide system-type dependencies)

**Comment by puyt** [comment]
> As for filtering dependencies - which dependencies do you want to hide? There is an option to only show dependencies that do have a story written for them (so it will hide system-type dependencies)

Oh right I totally forgot about that, I turned the option off to see if it'd make any difference 😅

**Comment by atanasster** [comment]
@puyt - is this how you wanted to see it working:

![grab97](https://user-images.githubusercontent.com/6075606/90335864-8e392700-dfe0-11ea-8416-60e115b6df1d.jpg)

**Comment by atanasster** [comment]
A release 2.1.1 should address the vue/sb6 support. Please confirm how it works for you.

I also added a bit of docs on the excludeFn parameter for dependecnies tables

**Comment by puyt** [comment]
> @puyt - is this how you wanted to see it working:
> 
> ![grab97](https://user-images.githubusercontent.com/6075606/90335864-8e392700-dfe0-11ea-8416-60e115b6df1d.jpg)

Isn't BIcon a dependency for BButton instead of dependent and vice versa? Since BIcon is required in BButton in orde to make it work?

Thanks again!

**Comment by atanasster** [comment]
ooops, you are right - the solution for vue a bit of a hack and I fixed it now. Please try 2.1.2

![grab98](https://user-images.githubusercontent.com/6075606/90336413-75327500-dfe4-11ea-877e-ed6b60475b27.jpg)

**Comment by puyt** [comment]
Looks good for dependencies :+1: But the `dependents` aren't detected yet I think?
 In BIcon there should be a dependent for BButton as seen in your design system example for AvatarList & Avatar [link](https://atanasster.github.io/storybook-addon-deps/?path=/docs/design-system-avatarlist--short)

Not sure how much work/different it is for vue though and i mostly needed dependencies so i'm already happy :+1:

**Comment by atanasster** [comment]
yeah, thats why i said its a bit of a hack. Since you are ok for now, I will postpone looking for a real solution for this issue with vue as I am a bit busy with other projects atm.

**Comment by puyt** [comment]
Sure thanks for the fast update :+1:

**Comment by atanasster** [comment]
@puyt - ok, I couldn't leave it :)

Can you please try 2.1.3 - its still the hacky solution using vue's component.components but should show correctly dependents for now.

![grab99](https://user-images.githubusercontent.com/6075606/90361712-94beb180-e067-11ea-8d9c-5b2a1bbba543.jpg)

**Comment by puyt** [comment]
@atanasster heh :stuck_out_tongue: It works, thanks a lot :+1: :smile:
