### ISSUE TITLE
Needs update for Storybook 6.2+

### ISSUE THREAD

**Issue by Bram-Zijp** [atanasster/storybook-addon-deps#15]
This module needs an update for Storybook 6.2+. A few things have changed making this addon incompatible. I really like the idea of this addon though. I plan on managing a large library with loads of dependents. Would like to get an overview of components touched when changing something.

Is someone gonna pick this up?

**Comment by atanasster** [comment]
Thanks - i would gladly accept PRs, but do you have a sample project that shows the error? 6.2 is a minor version upgrade and shouldn’t introduce incompatible changes afaik.

**Comment by puyt** [comment]
@atanasster You can use my example zip from #11 

I get the following error after running `npx sb@next upgrade` & `npm run storybook`

![image](https://user-images.githubusercontent.com/3668615/114672267-456b7680-9d05-11eb-8c6e-dcf54c40ae8d.png)

**Comment by atanasster** [comment]
thanks @puyt I will try to get some free time soon and will let you know.

**Comment by atanasster** [comment]
Thanks guys, just released v 2.2.0, should be compatible with 6.2

**Comment by puyt** [comment]
> Thanks guys, just released v 2.2.0, should be compatible with 6.2

Works for me, thanks a lot! :+1:
