### ISSUE TITLE
Dependencies not found (React)

### ISSUE THREAD

**Issue by donaldpipowitch** [atanasster/storybook-addon-deps#2]
Thank you very much for this addon. I tried it out in our codebase, but it didn't seem to work. I created a small demo project to show that dependencies are not found. https://github.com/donaldpipowitch/storybook-addon-deps-bug

`$ git clone https://github.com/donaldpipowitch/storybook-addon-deps-bug.git && cd storybook-addon-deps-bug && yarn && yarn install`

Any idea why? I thought I configured everything correctly.

Thank you :)

**Comment by roman-balzer** [comment]
Also not working for me.

Deps Tab is also not showing beside Docs Tab, despite configuring preset-explorer

**Comment by donaldpipowitch** [comment]
@roman-balzer Seems to be a different issue however.

**Comment by atanasster** [comment]
Thanks a lot, i will check your repro today.

@roman-balzer - can you point me also to a repro.

**Comment by atanasster** [comment]
@donaldpipowitch really sorry for the delay, i was pretty busy and hope to get to your repo this week.

As a compensation, i will share here first what I have been busy with - “1-line functional testing”

https://gifyu.com/image/qtbT

**Comment by donaldpipowitch** [comment]
Don't worry take the time you need. And niiiiice idea with the one line controls 👍

**Comment by atanasster** [comment]
@donaldpipowitch - found it, by default the plugin filters stories as the usual names (stories.tsx etc). You ca change the filtering options from the options of `storybook-dep-webpack-plugin`, but i completely forgot the list the options in the readme, So I have now updated the readme - can you please check the last section [Options.filter](https://github.com/atanasster/storybook-addon-deps#options) - and you should be able to adjust the re mask to your needs,

If not, the easiest 'fix' would be to rename your stories to the default naming too :)

Anyway, here is a screenshot of the addon working now:

![grab45](https://user-images.githubusercontent.com/6075606/73716531-41959a80-46e5-11ea-8619-353489dbe982.jpg)

**Comment by atanasster** [comment]
If you also want to play with how much details to display, you can use more of a docs-only type setup like here:

https://github.com/storybookjs/design-system/blob/57cc9176a788efae9330a348744ed22114360b40/.storybook/preview.js#L14

**Comment by donaldpipowitch** [comment]
I'll close for now as this will probably solve my issue. Thanks
