### ISSUE TITLE
Is it works with storybook 6 ?

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [atanasster/storybook-addon-deps#4]
I'm getting an error 
<img width="1940" alt="Screenshot 2020-02-14 at 18 14 18" src="https://user-images.githubusercontent.com/3968373/74548068-d6a25a00-4f55-11ea-968f-578f7685c8c1.png">

**Comment by atanasster** [comment]
Thanks for reporting - can you please try removing your node_modules and re-install?and make sure all your storybook packages are on the same version.

**Comment by atanasster** [comment]
Sorry - just saw your question about version 6 - not sure if thats the issue. I do have theming as a peer dependency https://github.com/atanasster/storybook-addon-deps/blob/555d3c132dab4615e1d080d8e01424778213a5b7/package.json#L36

**Comment by atanasster** [comment]
closing for now, usually this issue is solved by removing the  node_modules and re-installing storybook
