### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by tim-thaler** [atanasster/storybook-addon-deps#7]
Hello @atanasster, thanks for your work! I tried to get it to work on windows 10, but without success. I made some debugging and every dependency seems to be collected but it is not shown in the frontend explorer. I used the same configuration on a linux machine and it worked. 
Any idea what it might be? I tried to start storybook as well with "cross-env".

Thanks in advance
Tim

**Comment by atanasster** [comment]
Thanks @tim-thaler - nothing comes to mind about differences under windows.

Do you see the component prop tables in the storybook docs page under windows?

**Comment by tim-thaler** [comment]
I can see it. I hope that my further investigations will bring some more details. So stay tuned.
Thanks

**Comment by atanasster** [comment]
Thanks a lot, let me know your further findings
