### ISSUE TITLE
DependanciesTable not working in MDX stories.

### ISSUE THREAD

**Issue by macca-pakka** [atanasster/storybook-addon-deps#9]
Loving this plugin. 

The DependanciesTable works fine when stories are written in CSF format but when writing stories in MDX format and importing the `<DependanciesTable of={component}>` component.

The table shows up but dependencies / dependants are never found. 

Please halp

**Comment by atanasster** [comment]
Thanks for the feedback.

I do have an mdx story example https://github.com/atanasster/storybook-addon-deps/blob/master/.storybook/stories/Button.stories.mdx

Any chance you can check what is different in your setup?

**Comment by macca-pakka** [comment]
Thanks for the fast reply!

It was the following;

Doesn't Work
<Meta title="3. Components/Bullet" component:  {Bullet} />

Works
<Meta title="3. Components/Bullet" parameters={{component:  Bullet }} />

**Comment by danmindru** [comment]
@macca-pakka seeing the same. Your suggestion to use `parameters` also worked for me.
storybook @ 5.3.18
addon-deps @ 2.0.0

**Comment by atanasster** [comment]
@danmindru @macca-pakka thanks for the patience.

It seems this is not fixed in storybook6 beta.0. 

There is a new version 2.0.1 of the plugin that is brought up to date with the beta - can you please try and open a new issue if it still does not work for you.
